language: node_js
node_js:
  - "10"
script:
  - yarn lint
  - yarn test
deploy:
  provider: firebase
  project: x-2019-08-31-test
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: release
  skip_cleanup: true
